# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/dealdb
spring.datasource.username=postgres
spring.datasource.password=0000

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# FILE UPLOAD
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ERROR HANDLING
server.error.include-message=always
server.error.include-binding-errors=always

# ? EMAIL OTP CONFIG (ADDED)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shubhambgkr2018@gmail.com
spring.mail.password=tcjtturxabdfcjlt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true